site_name: habplus
site_description: A web api extension for habitica for additional quests
repo_url: https://github.com/the16thpythonist/habplus
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/the16thpythonist">the16thpythonist</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
